# Generated by Django 5.2.8 on 2025-12-05 09:27

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('card', 5), ('heading', 6), ('paragraph', 7)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'help_text': 'If the page above is selected, that will be used first.', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_page', 3), ('button_url', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 7: ('wagtail.blocks.RichTextBlock', (), {})}),
        ),
    ]
